### ISSUE TITLE
npm install error for mocha

### ISSUE THREAD

**Issue by fmegclark** [juliangruber/brace-expansion#37]
Hi,

I am currently getting this error when I try to install mocha which has brace-expansion as a dependency:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mocha" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: balanced-match@^1.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0, 0.0.1, 0.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'brace-expansion'
npm ERR! notarget 

Please help!

**Comment by juliangruber** [comment]
That's interesting. Can you show me the output of

```bash
npm show balanced-match version
```

For me it shows `1.0.0`. https://www.npmjs.com/package/balanced-match reflects that also.

**Comment by juliangruber** [comment]
Maybe this is solved by now and npm was just a bit behind in replication.

**Comment by fmegclark** [comment]
Hi,
Thanks for responding.
I just ran npm install and still got:
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mocha" "--save"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: balanced-match@^1.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.1, 0.2.0, 0.1.0, 0.0.1, 0.0.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'brace-expansion'
npm ERR! notarget

Should I wait for a bit?

**Comment by fmegclark** [comment]
Hi,
Thank you again for replying to my issue.  I am still getting the same error.
Thanks!

**Comment by nmOobert** [comment]
We just ran into this issue. Our corp proxy didn't get the update that was pushed for whatever reason. Are you behind a proxy? If so, that maybe your issue.

**Comment by fmegclark** [comment]
Thanks for this suggestion.  This worked!
